### ISSUE TITLE
Middleman restarts when pushing Episode

### ISSUE THREAD

**Issue by FLIPNEUS** [genial123/middleman#9]
Over the last couple of days (quite possibly since the update to 0.5.3), I'm having a strange issue on the BTN-side when using Middleman. Almost every time that Middleman has found an episode in SickBeard that I want to download, it seems to restart itself, without actually pushing the episode. A small extract from my log:

2015-01-06 04:03:07 - debug: [BTNIRC] Match show:               Sleepy Hollow (2015)
2015-01-06 04:03:07 - debug: [BTNIRC] Match type:               S02E12 - mkv / x264 / hdtv / 720p
2015-01-06 04:03:07 - debug: [BTNIRC] Match name:               Sleepy.Hollow.S02E12.720p.HDTV.x264-IMMERSE
2015-01-06 04:03:07 - debug: [BTNIRC] Match torrent ID:         465425
2015-01-06 04:03:07 - debug: [BTNIRC] Match language:           english
2015-01-06 04:03:07 - debug: [BTNIRC] Shows cached recently, not going to query SickBeard
2015-01-06 04:03:07 - debug: [BTNIRC] Current set of shows is 12.8 minutes old (limit: 60 min)
2015-01-06 04:03:07 - debug: [BTNIRC] Sleepy Hollow received a score of 100% (>= 85%)
2015-01-06 04:03:07 - info: [BTNIRC] Found name-match with SickBeard: Sleepy Hollow - S02E12
2015-01-06 04:03:07 - debug: [BTNIRC] Determined quality to be: HDTV
2015-01-06 04:03:07 - info: [BTNIRC] We want that quality (HDTV), checking if SickBeard already has any episodes
2015-01-06 04:03:07 - debug: [BTNIRC] http://localhost:8081/sickbeard/api/3e4f999612122cf13db987c1c7ccba9d/?cmd=episode&tvdbid=269578&season=2&episode=12
2015-01-06 04:03:07 - info: [BTNIRC] Could not find an existing episode of Sleepy Hollow - S02E12 - we want it!
2015-01-06 04:03:07 - debug: [BTNIRC] Making sure ID from BTN matches with SickBeard...
2015-01-06 04:03:07 - debug: [BTNIRC] Pushing new search (simple) into queue in 0 second(s)...
2015-01-06 04:03:07 - debug: [BTNIRC] Sending BTN API-call to look up torrent with id: 465425
2015-01-06 04:03:07 - debug: [BTNIRC] Halting search-queue for 5 seconds to avoid flooding
2015-01-06 04:03:08 - info: [DISPATCH] Trying to check Middleman version using Git
2015-01-06 04:03:08 - debug: [DISPATCH] Middleman current version: 0.5.3, newest version: 0.5.3
2015-01-06 04:03:08 - info: [DISPATCH] Middleman is up-to-date, running version: 0.5.3 - nice!
2015-01-06 04:03:08 - info: [DISPATCH] Starting module BTNIRC
2015-01-06 04:03:08 - info: [BTNIRC] Connecting to FLIPNEUS|AutoDL@irc.broadcasthe.net:6667...
2015-01-06 04:03:08 - info: [BTNIRC] Listening for announces...
2015-01-06 04:03:10 - info: [BTNIRC] Connected to irc.broadcasthe.net:6667!
2015-01-06 04:03:10 - info: [BTNIRC] Identifying with NickServ...
2015-01-06 04:03:10 - info: [BTNIRC] Identified with NickServ!
2015-01-06 04:03:10 - info: [BTNIRC] Joined channel #BTN-WhatAuto
2015-01-06 04:03:10 - info: [BTNIRC] Joined channel #btn-announce

The episode in the end never gets pushed to SickBeard and is not being downloaded either. It seems to be doing this for pretty much every single episode... I have no idea where this could be coming from.

**Comment by genial123** [comment]
Looks like something is crashing alright, could you check your ~/.middleman/logs/forever.debug.log? It'll contain crash reports from the currently running Middleman session.

**Comment by FLIPNEUS** [comment]
Current contents of forever.debug.log:

/opt/middleman/lib/provider/btn/btn-http.js:21
                        if ((typeof data['torrents'] !== 'undefined') && (typeof data['torrents'][i
                                        ^
TypeError: Cannot read property 'torrents' of null
    at /opt/middleman/lib/provider/btn/btn-http.js:21:20
    at /opt/middleman/node_modules/btn-api/lib/btn.js:46:5
    at IncomingMessage.<anonymous> (/opt/middleman/node_modules/btn-api/lib/btn.js:108:5)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

/opt/middleman/lib/provider/btn/btn-http.js:21
                        if ((typeof data['torrents'] !== 'undefined') && (typeof data['torrents'][i
                                        ^
TypeError: Cannot read property 'torrents' of null
    at /opt/middleman/lib/provider/btn/btn-http.js:21:20
    at /opt/middleman/node_modules/btn-api/lib/btn.js:46:5
    at IncomingMessage.<anonymous> (/opt/middleman/node_modules/btn-api/lib/btn.js:108:5)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

/opt/middleman/lib/provider/btn/btn-http.js:21
                        if ((typeof data['torrents'] !== 'undefined') && (typeof data['torrents'][i
                                        ^
TypeError: Cannot read property 'torrents' of null
    at /opt/middleman/lib/provider/btn/btn-http.js:21:20
    at /opt/middleman/node_modules/btn-api/lib/btn.js:46:5
    at IncomingMessage.<anonymous> (/opt/middleman/node_modules/btn-api/lib/btn.js:108:5)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

**Comment by FLIPNEUS** [comment]
Do you need any more information on my end to fix this?
